FROM oven/bun:latest

WORKDIR /app

COPY . .

WORKDIR /app/backend

RUN bun install


EXPOSE 1000



CMD [ "bunx", "prisma", "migrate", "deploy", "&&", "bunx", "prisma", "generate", "&&", "bun", "run", "dev" ]




